package com.theone.sc;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/Servlet2")
public class Servlet2 extends HttpServlet{
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
     System.out.println("Servlet 1 request now received by Servlet 2");
     response.getWriter().print("Actaully response has generated by Servlet 2");
     System.out.println("Servlet 2 generate response and sendback to servlet 1");
   }
}
